export const HOME_VIDEOS_SUCESS = 'HOME_VIDEOS_SUCCESS';
export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST';
export const HOME_VIDEOS_FAIL = 'HOME_VIDEOS_FAIL';

export const RESULTS_VIDEOS_SUCESS = 'RESULTS_VIDEOS_SUCCESS';
export const RESULTS_VIDEOS_REQUEST = 'RESULTS_VIDEOS_REQUEST';
export const RESULTS_VIDEOS_FAIL = 'RESULTS_VIDEOS_FAIL';
