export const SINGLE_VIDEO_REQUEST = 'SINGLE_VIDEO_REQUEST ';
export const SINGLE_VIDEO_SUCCESS = 'SINGLE_VIDEO_SUCCESS ';
export const SINGLE_VIDEO_FAIL = 'SINGLE_VIDEO_FAIL ';
export const GET_SINGLE_VIDEO_DATA = 'GET_SINGLE_VIDEO_DATA';
