export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const LAST_VIDEO_WATCHED = 'LAST_VIDEO_WATCHED';
export const SET_SEARCH_RELARED_VIDEOS = 'SET_SEARCH_RELARED_VIDEOS';
export const SET_LOADING = 'SET_LOADING';
